version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      labels:
          - 'dependencies'
      commit-message:
          prefix: 'build(deps)'

    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      labels:
          - 'dependencies'
      commit-message:
          prefix: 'build(deps)'
      ignore:
          - dependency-name: '*'
            update-types:
                - 'version-update:semver-major'

      groups:
          framework:
              patterns:
                  - 'nuxt'
                  - 'vue-tsc'
              update-types:
                  - 'minor'
                  - 'patch'

          linting-and-formatting:
              patterns:
                  - 'eslint'
                  - 'eslint-config-prettier'
                  - 'eslint-plugin-simple-import-sort'
                  - 'eslint-plugin-vue'
                  - 'prettier'
                  - 'stylelint'
                  - 'stylelint-config-standard'
              update-types:
                  - 'minor'
                  - 'patch'

          typings:
              patterns:
                  - '@types/node'
              update-types:
                  - 'minor'
                  - 'patch'

          build-tools:
              patterns:
                  - 'typescript'
                  - 'ts-node'
                  - 'typescript-eslint'
              update-types:
                  - 'minor'
                  - 'patch'

          postcss:
              patterns:
                  - 'postcss'
                  - 'postcss-import'
                  - 'postcss-load-config'
                  - 'postcss-nested'
                  - 'autoprefixer'
              update-types:
                  - 'minor'
                  - 'patch'

          nuxt-ecosystem:
              patterns:
                  - '@nuxt/devtools'
                  - '@nuxt/eslint'
                  - '@nuxt/eslint-config'
                  - '@nuxt/types'
              update-types:
                  - 'minor'
                  - 'patch'
