name: Build

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

concurrency:
    group: build-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        env:
            NUXT_PUBLIC_SITE_URL: ${{ secrets.NUXT_PUBLIC_SITE_URL }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Set up Node workspace
              uses: ./.github/actions/setup-node-workspace

            - name: Build
              run: npm run build
