name: Build

on: [push]

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js environment
        uses: actions/setup-node@v6
        with:
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Compile and build
        run: npm run build
